### ISSUE TITLE
Problems with emulator on Windows

### ISSUE THREAD

**Issue by rupak0577** [processing/processing-android#382]
1) Processing keeps waiting indefinitely for the emulator to become available even after it has completed the boot process. This is probably because [this line](https://github.com/processing/processing-android/blob/master/src/processing/mode/android/EmulatorController.java#L149) is not getting executed which means there is a problem with `runADB()` on Windows. Maybe Processing is trying to execute `adb` instead of `adb.exe`?

2) Rerunning a sketch after closing the emulator does not restart it and Processing keeps waiting for it to become available.

3) The watch emulator does not start while the phone emulator is running.

**Comment by codeanticode** [comment]
@rupak0577 Ok, interesting point. I have been able to run the emulator on Windows 10 without any errors, although I can see that indeed the command in runABD() includes `adb` instead of `adb.exe`. Did you try adding the extensions?

Actually, I had a similar problem with zipalign, which I solved by[ adding the .exe](https://github.com/processing/processing-android/blob/master/src/processing/mode/android/AndroidSDK.java#L340), so this might be the solution here as well. I'm surprised that I can execute `abd` on my computer. Any thoughts?

**Comment by rupak0577** [comment]
@codeanticode The issue is because Processing tries to run `adb` as a system-wide command and not directly from the sdk directory, like it was doing with the emulator.

**Comment by codeanticode** [comment]
ok, made [these changes](https://github.com/processing/processing-android/commit/7c1542eb3b5dbb891c19af37ade4791d6f17018b) so runADB is not static anymore so it can use the platformTools path... did a quick test and seems to be ok, could you double check on your system?

Still, the process launch/exec seems a bit messy, some parts use [ProcessHelper(adbCmd).execute()](https://github.com/processing/processing-android/blob/master/src/processing/mode/android/AndroidSDK.java#L711), while others [Runtime.getRuntime().exec(cmd)](https://github.com/processing/processing-android/blob/master/src/processing/mode/android/Device.java#L334), not sure why the reason why. This [generateAdbCommand()](https://github.com/processing/processing-android/blob/master/src/processing/mode/android/Device.java#L415) method is kind of confusing too. Would be nice to refactor these things, so process execution is done consistently.

**Comment by rupak0577** [comment]
Unfortunately it is still not working(no problems on Linux though). Seems like the problem is elsewhere.

**Comment by rupak0577** [comment]
Can't believe it was the `\n`...All issues fixed with commit c7b1139
